version: '3'

services:
  api_events_service:
    build:
      context: ./api_events_service
    ports:
      - "5000:5000"
    networks:
      - api_network

  api_marketplace:
    build:
      context: ./api_marketplace
    ports:
      - "8000:8000"
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
